kind: Service
apiVersion: v1
metadata:
  name: helloworld-nodejs
  labels:
    net.beedemo.deploy.type: workshop
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: helloworld-nodejs
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: helloworld-nodejs-production
  labels:
    net.beedemo.deploy.type: workshop
spec:
  replicas: 1
  template:
    metadata:
      name: helloworld-nodejs
      labels:
        net.beedemo.deploy.type: workshop
        app: helloworld-nodejs
        env: production
    spec:
      containers:
      - name: helloworld-nodejs
        image: 946759952272.dkr.ecr.us-east-1.amazonaws.com/myjenkinsworld/helloworld-nodejs
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
        imagePullPolicy: Always
        ports:
        - name: public
          containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-nodejs
  labels:
    net.beedemo.deploy.type: workshop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /helloworld-nodejs
        backend:
          serviceName: helloworld-nodejs
          servicePort: 80
    host: prod.workshop.beedemo.net
